language: ruby
cache:
  bundler: true
sudo: false
dist: trusty
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install: gem install bundler -v 1.16.1
script: ./.travis.sh
env:
  matrix:
    - TEST_GROUP=prereq
    - TEST_GROUP=1
matrix:
  fast_finish: true
